---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    :80

    @http {
        header "X-Forwarded-Proto" "http"
    }
    redir @http "https://{host}{uri}"

    header /status {
      "Content-Type" "application/json"
    }
    respond /status "{ \"location\": \"Kubernetes\" }"
